"""Built-in demo file metadata for deployments where cloud storage is empty."""

from __future__ import annotations

from typing import Dict, List


DEMO_FILES: List[Dict[str, object]] = [
    {"name": "sample_file_01.txt", "size_bytes": 251658, "label": "0.24 MB"},
    {"name": "sample_file_02.txt", "size_bytes": 5242880, "label": "5.00 MB"},
    {"name": "sample_file_03.txt", "size_bytes": 104857, "label": "0.10 MB"},
    {"name": "sample_file_04.txt", "size_bytes": 2097152, "label": "2.00 MB"},
    {"name": "sample_file_05.txt", "size_bytes": 1048576, "label": "1.00 MB"},
    {"name": "sample_file_06.txt", "size_bytes": 513802, "label": "0.49 MB"},
    {"name": "sample_file_07.txt", "size_bytes": 104857, "label": "0.10 MB"},
    {"name": "sample_file_08.txt", "size_bytes": 2097152, "label": "2.00 MB"},
    {"name": "sample_file_09.txt", "size_bytes": 513802, "label": "0.49 MB"},
    {"name": "sample_file_10.txt", "size_bytes": 251658, "label": "0.24 MB"},
    {"name": "sample_file_11.txt", "size_bytes": 2097152, "label": "2.00 MB"},
    {"name": "sample_file_12.txt", "size_bytes": 1048576, "label": "1.00 MB"},
    {"name": "sample_file_13.txt", "size_bytes": 1048576, "label": "1.00 MB"},
    {"name": "sample_file_14.txt", "size_bytes": 2097152, "label": "2.00 MB"},
    {"name": "sample_file_15.txt", "size_bytes": 513802, "label": "0.49 MB"},
]


def get_demo_file_record(filename: str):
    for record in DEMO_FILES:
        if record["name"] == filename:
            return record
    return None


def list_demo_files():
    return [
        {
            "name": record["name"],
            "size": record["size_bytes"],
            "source": "demo",
        }
        for record in DEMO_FILES
    ]


def build_demo_file_bytes(filename: str) -> bytes:
    record = get_demo_file_record(filename)
    if not record:
        return b""

    size_bytes = int(record["size_bytes"])
    header = (
        f"Demo file: {filename}\n"
        f"This file is generated by the Vercel fallback dataset because the Supabase bucket is empty.\n"
        f"Requested size: {record['label']}\n\n"
    ).encode("utf-8")

    if size_bytes <= len(header):
        return header[:size_bytes]

    filler = (f"{filename} | Cloud Computing and Scaling Lab\n").encode("utf-8")
    output = bytearray(header)

    while len(output) < size_bytes:
        remaining = size_bytes - len(output)
        output.extend(filler[:remaining])

    return bytes(output)